#WAP to generate a random num
#tell the user that 0 is generated by print tail
# head when 1 is generated

import random

def toss():

	list1 = [0,1,2,3]
	toss = random.choice(list1)
	if toss == 0:
		print("TAIL")
	elif toss == 1:
		print("HEAD")
	else:
		print("invalid")
	print(toss)
toss();
